/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** create */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          /**
           * @example {
           *       "email": "test@example.com",
           *       "password": "password123"
           *     }
           */
          "application/x-www-form-urlencoded": {
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description 200 OK が返り、JWTトークンが含まれていること */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "data": {
             *         "user": {
             *           "id": 419,
             *           "name": "Test User",
             *           "email": "test@example.com"
             *         }
             *       },
             *       "meta": {
             *         "token": "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0MTksImV4cCI6MTc3NzkwNDY5NH0.d_PGgQsEkGc-WHHGXu-ngUG2WlDLtUHvZAOiQ0H7tws"
             *       }
             *     }
             */
            "application/json": {
              data: {
                user: {
                  id: number;
                  name: string;
                  email: string;
                };
              };
              meta: {
                token: string;
              };
            };
          };
        };
        /** @description 401 Unauthorized が返ること */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "unauthorized",
             *           "message": "認証に失敗しました。"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** me */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description ユーザー情報が返ること */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "data": {
             *         "user": {
             *           "id": 427,
             *           "name": "Me User",
             *           "email": "me@test.com"
             *         }
             *       }
             *     }
             */
            "application/json": {
              data: {
                user: {
                  id: number;
                  name: string;
                  email: string;
                };
              };
            };
          };
        };
        /** @description 401 Unauthorized が返ること */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "unauthorized",
             *           "message": "認証が必要です。"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/signup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** create */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          /**
           * @example {
           *       "user": {
           *         "name": "Test User",
           *         "email": "test@exaple.com",
           *         "password": "password123",
           *         "password_confirmation": "password123"
           *       }
           *     }
           */
          "application/x-www-form-urlencoded": {
            user: {
              name: string;
              email: string;
              password: string;
              password_confirmation: string;
            };
          };
        };
      };
      responses: {
        /** @description 201 Created が返り、JWTトークンが含まれていること */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "data": {
             *         "user": {
             *           "id": 426,
             *           "name": "Test User",
             *           "email": "test@exaple.com"
             *         }
             *       },
             *       "meta": {
             *         "token": "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0MjYsImV4cCI6MTc3NzkwNDY5NH0.B-clH4Ulabg_px-ozVf2P0RCjQdiXp1kWu76-pypQO0"
             *       }
             *     }
             */
            "application/json": {
              data: {
                user: {
                  id: number;
                  name: string;
                  email: string;
                };
              };
              meta: {
                token: string;
              };
            };
          };
        };
        /** @description 422 Unprocessable Entity が返り、エラーが含まれていること */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "validation_error",
             *           "message": "Password confirmation doesn't match Password"
             *         },
             *         {
             *           "code": "validation_error",
             *           "message": "Name can't be blank"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/posts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** index */
    get: {
      parameters: {
        query?: {
          /** @example Rails */
          q?: string;
          /** @example unknown-tag */
          tag?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 200 OK を返し、空配列を返すこと */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "data": {
             *         "posts": []
             *       }
             *     }
             */
            "application/json": {
              data: {
                posts: {
                  id: number;
                  user_id: number;
                  title: string;
                  body: string;
                  created_at: string;
                  tags: {
                    id: number;
                    name: string;
                  }[];
                  like_count: number;
                  liked_by_current_user: boolean;
                }[];
              };
            };
          };
        };
      };
    };
    put?: never;
    /** create */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          /**
           * @example {
           *       "post": {
           *         "title": "重複タグ",
           *         "body": "本文",
           *         "tag_names": [
           *           "python",
           *           "python"
           *         ]
           *       }
           *     }
           */
          "application/x-www-form-urlencoded": {
            post: {
              title: string;
              body: string;
              tag_names?: string[];
            };
          };
        };
      };
      responses: {
        /** @description 重複を除いて1つのタグとして扱うこと */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "data": {
             *         "post": {
             *           "id": 358,
             *           "user_id": 401,
             *           "title": "重複タグ",
             *           "body": "本文",
             *           "created_at": "2026-05-03T14:24:54.013Z",
             *           "tags": [
             *             {
             *               "id": 127,
             *               "name": "python"
             *             }
             *           ],
             *           "like_count": 0,
             *           "liked_by_current_user": false
             *         }
             *       }
             *     }
             */
            "application/json": {
              data: {
                post: {
                  id: number;
                  user_id: number;
                  title: string;
                  body: string;
                  created_at: string;
                  tags: {
                    id: number;
                    name: string;
                  }[];
                  like_count: number;
                  liked_by_current_user: boolean;
                };
              };
            };
          };
        };
        /** @description 401 Unauthorized が返る */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "unauthorized",
             *           "message": "認証が必要です。"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
        /** @description 422 Unprocessable Content が返ること */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "validation_error",
             *           "message": "Tag names can't include blank values"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/posts/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** show */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @example 9999 */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 200 OK が返り、該当記事の詳細が取得できること */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "data": {
             *         "post": {
             *           "id": 353,
             *           "user_id": 395,
             *           "title": "記事タイトル",
             *           "body": "記事の本文",
             *           "created_at": "2026-05-03T14:24:53.827Z",
             *           "tags": [],
             *           "like_count": 0,
             *           "liked_by_current_user": false,
             *           "comments": []
             *         }
             *       }
             *     }
             */
            "application/json": {
              data: {
                post: {
                  id: number;
                  user_id: number;
                  title: string;
                  body: string;
                  created_at: string;
                  tags: unknown[];
                  like_count: number;
                  liked_by_current_user: boolean;
                  comments: {
                    id: number;
                    user_id: number;
                    body: string;
                    created_at: string;
                  }[];
                };
              };
            };
          };
        };
        /** @description 404 Not Found が返ること */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "not_found",
             *           "message": "指定されたリソースが見つかりません"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** destroy */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @example 373 */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 200 OK が返り、記事が削除されること */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "data": {
             *         "message": "記事を削除しました"
             *       }
             *     }
             */
            "application/json": {
              data: {
                message: string;
              };
            };
          };
        };
        /** @description 401 Unauthorized が返ること */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "unauthorized",
             *           "message": "認証が必要です。"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
        /** @description 403 Forbidden が返り、記事は削除されないこと */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "forbidden",
             *           "message": "権限がありません"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** update */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @example 367 */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          /**
           * @example {
           *       "post": {
           *         "title": "更新タイトル",
           *         "body": "更新本文",
           *         "tag_names": [
           *           "vue"
           *         ]
           *       }
           *     }
           */
          "application/x-www-form-urlencoded": {
            post: {
              title: string;
              body: string;
              tag_names?: string[];
            };
          };
        };
      };
      responses: {
        /** @description タグが置き換わること */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "data": {
             *         "post": {
             *           "id": 367,
             *           "user_id": 411,
             *           "title": "更新タイトル",
             *           "body": "更新本文",
             *           "created_at": "2026-05-03T14:24:54.163Z",
             *           "tags": [
             *             {
             *               "id": 129,
             *               "name": "vue"
             *             }
             *           ],
             *           "like_count": 0,
             *           "liked_by_current_user": false
             *         }
             *       }
             *     }
             */
            "application/json": {
              data: {
                post: {
                  id: number;
                  user_id: number;
                  title: string;
                  body: string;
                  created_at: string;
                  tags: {
                    id: number;
                    name: string;
                  }[];
                  like_count: number;
                  liked_by_current_user: boolean;
                };
              };
            };
          };
        };
        /** @description 401 Unauthorized が返ること */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "unauthorized",
             *           "message": "認証が必要です。"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
        /** @description 403 Forbidden が返り、記事は更新されないこと */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "forbidden",
             *           "message": "権限がありません"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
        /** @description 422 Unprocessable Content が返り、更新されないこと */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "validation_error",
             *           "message": "Title can't be blank"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/v1/posts/{post_id}/comments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** create */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @example 999999 */
          post_id: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          /**
           * @example {
           *       "comment": {
           *         "body": "有効なコメント"
           *       }
           *     }
           */
          "application/x-www-form-urlencoded": {
            comment: {
              body: string;
            };
          };
        };
      };
      responses: {
        /** @description コメントが作成され、201 Created が返ること */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "data": {
             *         "comment": {
             *           "id": 29,
             *           "post_id": 323,
             *           "user_id": 365,
             *           "body": "有効なコメント",
             *           "created_at": "2026-05-03T14:24:53.189Z"
             *         }
             *       }
             *     }
             */
            "application/json": {
              data: {
                comment: {
                  id: number;
                  post_id: number;
                  user_id: number;
                  body: string;
                  created_at: string;
                };
              };
            };
          };
        };
        /** @description 401 Unauthorized が返ること */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "unauthorized",
             *           "message": "認証が必要です。"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
        /** @description 404 Not Found が返ること */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "not_found",
             *           "message": "指定されたリソースが見つかりません"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
        /** @description コメントは作成されず、422 Unprocessable Entity が返ること */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "validation_error",
             *           "message": "Body can't be blank"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/posts/{post_id}/comments/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** destroy */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @example 33 */
          id: number;
          /** @example 329 */
          post_id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 200 OK が返り、コメントが削除されること */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "data": {
             *         "message": "コメントを削除しました"
             *       }
             *     }
             */
            "application/json": {
              data: {
                message: string;
              };
            };
          };
        };
        /** @description 401 Unauthorized が返ること */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "unauthorized",
             *           "message": "認証が必要です。"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
        /** @description 403 Forbidden が返り、コメントは削除されないこと */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "forbidden",
             *           "message": "権限がありません"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/posts/{post_id}/like": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** create */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @example 999999 */
          post_id: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          /** @example {} */
          "application/x-www-form-urlencoded": Record<string, never>;
        };
      };
      responses: {
        /** @description いいねが作成され、201 Created が返ること */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "data": {
             *         "like": {
             *           "id": 50,
             *           "post_id": 331,
             *           "user_id": 379,
             *           "created_at": "2026-05-03T14:24:53.505Z"
             *         },
             *         "like_count": 1
             *       }
             *     }
             */
            "application/json": {
              data: {
                like: {
                  id: number;
                  post_id: number;
                  user_id: number;
                  created_at: string;
                };
                like_count: number;
              };
            };
          };
        };
        /** @description 401 Unauthorized が返ること */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "unauthorized",
             *           "message": "認証が必要です。"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
        /** @description 404 Not Found が返ること */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "not_found",
             *           "message": "指定されたリソースが見つかりません"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
        /** @description いいねは作成されず、422 Unprocessable Content が返ること */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "validation_error",
             *           "message": "User has already been taken"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
      };
    };
    /** destroy */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @example 999999 */
          post_id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description いいねが削除され、200 OK が返ること */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "data": {
             *         "like_count": 0,
             *         "message": "いいねを取り消しました"
             *       }
             *     }
             */
            "application/json": {
              data: {
                like_count: number;
                message: string;
              };
            };
          };
        };
        /** @description 401 Unauthorized が返ること */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "unauthorized",
             *           "message": "認証が必要です。"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
        /** @description 404 Not Found が返ること */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "errors": [
             *         {
             *           "code": "not_found",
             *           "message": "いいねが見つかりません"
             *         }
             *       ]
             *     }
             */
            "application/json": {
              errors: {
                code: string;
                message: string;
              }[];
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** index */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description 200 OK を返し、空配列を返すこと */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "data": {
             *         "tags": []
             *       }
             *     }
             */
            "application/json": {
              data: {
                tags: {
                  id: number;
                  name: string;
                  created_at: string;
                }[];
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
